# Generated by Django 5.0.2 on 2024-02-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
